[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true 
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "preserve"

[fuzz]
runs = 256
max_test_rejects = 65536
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[profile.default]
env = { PRIVATE_KEY = "${PRIVATE_KEY}" }
src = "src"
test = "tests"
script = "scripts"
out = "out"
libs = [ "lib" ]
remappings = [ "forge-std/=lib/forge-std/src/", "token-types/=lib/token-types/src/"]
auto_detect_remappings = true
libraries = []
cache = true
cache_path = "cache"
broadcast = "broadcast"
allow_paths = []
include_paths = []
force = false
evm_version = "cancun"
gas_reports = [ "*",]
gas_reports_ignore = []
auto_detect_solc = true
offline = false
optimizer = true
optimizer_runs = 200
verbosity = 0
ignored_error_codes = [ 1878, 5574,]
deny_warnings = false
build_info = false
ffi = false
sender = "0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38"
tx_origin = "0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38"
initial_balance = "0xffffffffffffffffffffffff"
chain_id = 31337
block_number = 1
gas_limit = 9223372036854775807
gas_price = 0
block_base_fee_per_gas = 0
block_coinbase = "0x0000000000000000000000000000000000000000"
block_timestamp = 1
block_difficulty = 0
memory_limit = 33554432
extra_output = [ "storageLayout",]
extra_output_files = []
names = false
sizes = false
via_ir = false
no_storage_caching = false
bytecode_hash = "ipfs"
revert_strings = "default"
sparse_mode = false
[[profile.default.fs_permissions]]
access = "read-write"
path = "./"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}" }
