// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReservationByPaymasterRequest = { sender: string, vault_indexes_to_reserve: Array<string>, amounts_to_reserve: Array<string>, eth_payout_address: string, total_sats_input_inlcuding_proxy_fee: string, expired_swap_reservation_indexes: Array<string>, };
